Org-mode Testing Report
* Matrix Multiplication with GCC
  
** Abstract
Large matrix multiplications can be very handy considering 
the limitations of cache and the speed of the the RAM access.
This report is about conducting matrix multiplication with 
low level optimizations. Loop tiling and LLVM optimizations
are used in order to provide an acceptable result for a better
scheduling and work load reduction.

** Basic Matrix Multiplication
The first version of matrix multiplication is done with
 two arrays of integers(simply for testing). My computer is 
an Alienware 17 R5, and some of the hardware specifications are listed
in Table. 1:


| Params               | Value          |
|----------------------+----------------|
| Architecture:        |         x86_64 |
| CPU op-mode(s):      | 32-bit, 64-bit |
| Byte Order:          |  Little Endian |
| CPU(s):              |              8 |
| On-line CPU(s) list: |            0-7 |
| Thread(s) per core:  |              2 |
| Core(s) per socket:  |              4 |
| Socket(s):           |              1 |
| NUMA node(s):        |              1 |
| Vendor ID:           |   GenuineIntel |
| CPU family:          |              6 |
| Model:               |             60 |
| Stepping:            |              3 |
| CPU MHz:             |        901.875 |
| BogoMIPS:            |        4788.98 |
| Virtualization:      |           VT-x |
| L1d cache:           |            32K |
| L1i cache:           |            32K |
| L2 cache:            |           256K |
| L3 cache:            |          6144K |
| NUMA node0 CPU(s):   |            0-7 |


Represented below, is my code for basic matrix multiplication:
#+BEGIN_SRC c
for(m=0; m<i; ++m){
    for(n=0; n<k; ++n){
        for(l=0; l<j; ++l){
            result[m*k+n] += mat1[m*j+l]*mat2[l*k+n];
        }
    }
}
#+END_SRC
The code is not optimized in anyway, and I used array to represent a matrix simply 
because I already forgot how to allocate a 2 dimentional pointer. And this piece of code
is a little bit funny since I messed up the normal order of using m and n. Let's just
ignore that.

** COMMENT For Basic Multiplication

*** TODO Add pictures of your hardware here.
    DEADLINE: <2016-04-15 Fri>


** Loop Tiling Matrix Multiplication
Implementation of loop tiling is supposed to be a method of optimizing large 
matrix optimization.
*** Tiling Description
 As shown above I have a CPU with 8 cores and a lot of Cache of 
